<?php

/* This file is automatically generated and modified by phpMyBackupPro v.1.3. */ 

$CONF['sitename']="mySite";
$CONF['lang']="english";
$CONF['sql_host']="localhost";
$CONF['sql_user']="gfbclcom_db";
$CONF['sql_passwd']="gfbcl00991!Z";
$CONF['sql_db']="gfbclcom_db";
$CONF['ftp_use']="0";
$CONF['ftp_server']="localhost";
$CONF['ftp_user']="";
$CONF['ftp_passwd']="";
$CONF['ftp_path']="";
$CONF['ftp_pasv']="0";
$CONF['ftp_port']="21";
$CONF['ftp_del']="1";
$CONF['email_use']="0";
$CONF['email']="";
$CONF['stylesheet']="standard";
$CONF['date']="%x %X";
$CONF['del_time']="7";
$CONF['del_number']="5";
$CONF['timelimit']="0";
$CONF['confirm']="1";
$CONF['import_error']="1";
$CONF['no_login']="0";
$CONF['login']="0";

?>