<?
//Warning
$wording_lan = array();
$wording_lan["word"]["register"]["choosetitle"] = "Choose Title";
$wording_lan["word"]["register"]["mr"] = "Mr.";
$wording_lan["word"]["register"]["ms"] = "Ms.";
$wording_lan["word"]["register"]["mrs"] = "Mrs.";
$wording_lan["word"]["register"]["company"] = "Co.,Ltd.";
$wording_lan["word"]["register"]["limited"] = "Ltd.,Part.";
$wording_lan["word"]["register"]["other"] = "Other";

$wording_lan["tab2_sale_3338"] = "รายการโอนเงิน Ewallet สมาชิก";
$wording_lan["word"]["sale_editadd"]["typea"] = "ซื้อแบบปกติ";
$wording_lan["word"]["sale_editadd"]["typeb"] = "ซื้อแบบ Hold";
$wording_lan["customer_price"] = "ราคาขายปลีก";
$wording_lan["Stockist (Local Currency)"] = "สรุปยอดรายการขายและเติมเงิน Ewallet ผ่าน Stockist ";
$wording_lan["Stockist (Base Currency)"] = "สรุปยอดรายการขายและเติมเงิน Ewallet ผ่าน Stockist  (Base Currency)";
//woring
$wording_lan["Please select payment"] = "Please select payment";

$wording_lan["system allow to renew member 90 days before expire"] = "system allow to renew member 90 days before expire";
$wording_lan['tab4']['1_48'] = "Ewallet not enough";
$wording_lan["word"]["vip"]["mcode"] = "Member&nbsp;And&nbsp;Position";
$wording_lan["word"]["vip"]["point"] = "VIP&nbsp;Point";
$wording_lan["word"]["vip"]["point"]["report"] = "Report&nbsp;VIP&nbsp;Point";
$wording_lan["word"]["saving"] = "Saving";
$wording_lan["word"]["member"]["status"] = "Status";
$wording_lan["word"]["member"]["single"] = "Single";
$wording_lan["word"]["member"]["married"] = "Married";
$wording_lan["word"]["member"]["divorced"] = "Divorced";
$wording_lan["word"]["member"]["names"] = "Spouse's&nbsp;Name";
$wording_lan["word"]["passport"] = "Passport";
$wording_lan["word"]["logout"] = "Logout";
$wording_lan["register"] = "Member Register";
$wording_lan["buyitem"] = "Order Products";
$wording_lan["extendyear"] = "Extend(Year)";

//woring
$wording_lan["word"]["price"] = "Price";
$wording_lan["word"]["total"] = "Amount";

$wording_lan["word"]["province"] = "Province";
$wording_lan["word"]["amper"] = "Amper";
$wording_lan["word"]["tumbon"] = "Tumbon";
$wording_lan["word"]["to"] = "To";
$wording_lan["word"]["second"] = "Second.";
$wording_lan["word"]["plan"] = "Plan";
$wording_lan["word"]["show"] = "Show";
$wording_lan["word"]["print"] = "Print All";
$wording_lan["word"]["excel"] = "Create Excel";
$wording_lan["word"]["excel1"] = "Load Excel";
$wording_lan["word"]["search"] = "Search";
$wording_lan["word"]["selectdate"] = "Choose date";
$wording_lan["word"]["type"] = "Type";
$wording_lan["word"]["all"] = "All";
$wording_lan["word"]["plana"] = "คุณสมบัติ";
$wording_lan["word"]["status"] = "รักษายอด";
$wording_lan["word"]["rebate"] = "รักษายอดทันที";
$wording_lan["word"]["billonline"] = "บิลออนไลน์";
$wording_lan["word"]["billing"] = "บิลขายบริษัท";
$wording_lan["word"]["billhold"] = "บิลแจงยอด" ;
$wording_lan["word"]["billcancel"] = "บิลยกเลิก";	
$wording_lan["word"]["bilnormal"] = "บิลปกติ";
$wording_lan["word"]["billall"] = "บิลทั้งหมด";
$wording_lan["word"]["sano"] = "เลขบิลขาย";
$wording_lan["word"]["hono"] = "เลขบิลแจง";
$wording_lan["word"]["invent"] = "รหัสสาขา";
$wording_lan["word"]["date"] = "วันที่";
$wording_lan["word"]["mcode"] = "รหัสสมาชิก";
$wording_lan["word"]["spcode"] = "รหัสผู้แนะนำ";
$wording_lan["word"]["maker"] = "ผู้บันทึก";
$wording_lan["word"]["name"] = "ชื่อ";
$wording_lan["word"]["mdate"] = "วันสมัคร";
$wording_lan["word"]["quantity"] = "จำนวน";
$wording_lan["word"]["cash"] = "Cash";
$wording_lan["word"]["advance"] = "Advance";
$wording_lan["word"]["transferpayment"] = "Transfer&nbsp;Payment";
$wording_lan["word"]["creditcard"] = "Credit&nbsp;Card";
$wording_lan["word"]["BillSaleDiscount"] = "Bill&nbsp;Sale&nbsp;Discount";
$wording_lan["word"]["other"] = "Other";
$wording_lan["word"]["description"] = "Description";
$wording_lan["word"]["statuspayment"] = "สถานะการชำระเงิน";
$wording_lan["word"]["cancel"] = "ยกเลิก";
$wording_lan["word"]["pos_cur"] = "ตำแหน่ง";
$wording_lan["word"]["upa_code"] = "รหัสอัพไลน์";
$wording_lan["word"]["edit_member"] = "แก้ไข";
$wording_lan["word"]["add_member"] = "เพิ่มสมาชิก";
$wording_lan["word"]["add_data"] = "เพิ่มข้อมูล";
$wording_lan["word"]["look_member"] = "ดู";
$wording_lan["word"]["del_member"] = "ลบ";
$wording_lan["word"]["id_card"] = "ID Card";
$wording_lan["word"]["nodata"] = "ไม่พบข้อมูล";
$wording_lan["word"]["list"] = "List(s)";
$wording_lan["word"]["amount"] = "Amount";
$wording_lan["word"]["data"] = "Data(s)";
$wording_lan["word"]["each"] = "each";
$wording_lan["word"]["show"] = "Show";
$wording_lan["word"]["page"] = "Page(s)";
$wording_lan["word"]["page_show_hint"] = "Enter for custom show \n(ALL = Show All)";
$wording_lan["word"]["gotopage"] = "Go to Page";
$wording_lan["word"]["gotopage_hint"] = "Enter for Go to Page";
$wording_lan["word"]["sum_text"] = "Total";
$wording_lan["word"]["point"] = "PV";
$wording_lan["word"]["personal_score"] = "คะแนนส่วนตัว";
$wording_lan["word"]["nomember"] = "ไม่มีสมาชิก";
$wording_lan["word"]["branch"] = "Branch";
$wording_lan["word"]["bank"] = "Bank";
$wording_lan["word"]["acc_type"] = "Bank Type";
$wording_lan["word"]["acc_name"] = "Account Name";
$wording_lan["word"]["acc_no"] = "Account ID";
$wording_lan["word"]["mobile"] = "Mobile";
$wording_lan["word"]["email"] = "Email";
$wording_lan["word"]["birthday"] = "Birth Day";
$wording_lan["word"]["address"] = "Address";
$wording_lan["word"]["choosemember"] = "เลือกสมาชิก";
$wording_lan["word"]["del"] = "Delete";
$wording_lan["word"]["choose"] = "Choose";
$wording_lan["word"]["password"] = "Password";
$wording_lan["word"]["title"] = "Prefix";
$wording_lan["word"]["name_t"] = "Name";
$wording_lan["word"]["name_b"] = "Business Name";
$wording_lan["word"]["name_en"] = "Name(Eng)";
$wording_lan["word"]["sex"] = "Sex";
$wording_lan["word"]["sex_m"] = "Male";
$wording_lan["word"]["sex_w"] = "Female";
$wording_lan["word"]["national"] = "Nationality";
$wording_lan["word"]["home_t"] = "Telephone";
$wording_lan["word"]["fax"] = "Fax";
$wording_lan["word"]["option"] = "Note";
$wording_lan["word"]["option1"] = "จำเป็นต้องกรอกข้อมูล";
$wording_lan["word"]["beneficiaries"] = "Heir";
$wording_lan["word"]["relation"] = "Relationship";
$wording_lan["word"]["document"] = "Documents";
$wording_lan["word"]["copy_card"] = "ID Card";
$wording_lan["word"]["copy_acc"] = "Book Bank";
$wording_lan["word"]["zipcode"] = "Zip Code";
$wording_lan["word"]["side"] = "Left/Right";
$wording_lan["word"]["usercode"] = "Username";
$wording_lan["word"]["username"] = "Name";
$wording_lan["word"]["menusell"] = "เมนูขาย";
$wording_lan["word"]["menumember"] = "เมนูสมาชิก";
$wording_lan["word"]["menuvip"] = "VIP";
$wording_lan["word"]["menucom"] = "เมนูคำนวณ";
$wording_lan["word"]["menusys"] = "เมนูบริหารระบบ";
$wording_lan["word"]["subject"] = "Subject";
$wording_lan["word"]["look"] = "Look";
$wording_lan["word"]["open"] = "เปิด";
$wording_lan["word"]["close"] = "ปิด";
$wording_lan["word"]["ok"] = "ตกลง";
$wording_lan["word"]["cancel"] = "ยกเลิก";
$wording_lan["word"]["add"] = "เพิ่ม";
$wording_lan["word"]["edit"] = "แก้ไข";
$wording_lan["word"]["startdate"] = "วันเริ่มต้น";
$wording_lan["word"]["enddate"] = "วันสิ้นสุด";
$wording_lan["word"]["rcode"] = "วันสิ้นสุด";
$wording_lan["word"]["faststart"] = "แนะนำ";
$wording_lan["word"]["binary"] = "ไบนารี่";
$wording_lan["word"]["matching"] = "แมชชิ่ง";
$wording_lan["word"]["time"] = "เวลา";
$wording_lan["word"]["yokma"] = "ยกมา";
$wording_lan["word"]["moneyin"] = "เงินเข้า";
$wording_lan["word"]["moneyout"] = "เงินออก";
$wording_lan["word"]["balance"] = "Balance";
$wording_lan["word"]["user"] = "ผู้ใช้";
$wording_lan["word"]["pcode"] = "Product&nbsp;Code";
$wording_lan["word"]["pdesc"] = "Product&nbsp;Detail";
$wording_lan["word"]["price"] = "Price";
$wording_lan["word"]["pricenet"] = "Net&nbsp;Price";
$wording_lan["word"]["qty"] = "Amount";
$wording_lan["word"]["net"] = "Net&nbsp;Amount";
$wording_lan["word"]["unit"] = "Unit";
$wording_lan["word"]["stock"] = "ยอดคงเหลือ";
$wording_lan["word"]["packagecode"] = "รหัส Package";
$wording_lan["word"]["approve"] = "ตรวจสอบ";
$wording_lan["word"]["receive"] = "รับของ";
$wording_lan["word"]["shipping"] = "Shipping";
$wording_lan["word"]["sum"] = "จำนวนรวม";
$wording_lan["word"]["pick_up"] = "Pick up";
$wording_lan["word"]["no."] = "No.";

$wording_lan["w1"] = "Can not see it because it was not a member.";
$wording_lan["w2"] = "Back to flowchart members.";
$wording_lan["w3"] = "Can not see it because it does not find code.";
$wording_lan["w4"] = "Back to the tree of its members.";
$wording_lan["w5"] = "Can not see the level higher.";
$wording_lan["w6"] = "Can not see another line or higher levels.";
$wording_lan["w7"] = "Please type the code and click View membership structure.";
$wording_lan["w8"] = "Back to the sponsor tree's guide.";
$wording_lan["w9"] = "For Browser Safari also does not work perfectly, please use Internet Explorer 8 or more. ";
$wording_lan["w10"] = "Ewallet not enough.";
$wording_lan["w11"] = "Time left to fill";
$wording_lan["w12"] = "(Insert the name you want to find a counselor in the field and then press the [Search])";
$wording_lan["w13"] = "(Enter search to line up in a box and then press the [Search])";
$wording_lan["w14"] = "No Data.";
$wording_lan["w15"] = "Sorry, the security code invalid.";
$wording_lan["w16"] = "Timeout";
$wording_lan["w17"] = "Click Check for data validation.";
$wording_lan["w18"] = "Choose product from catalog and quantity required.";
$wording_lan["w19"] = "Can not find the item of bill number ";
$wording_lan["prod_enough"] = "Product is not enough";

//wording
$wording_lan["A"] = "Property";
$wording_lan["Q"] = "Maintain balance";
$wording_lan["C"] = "Maintain balance immediately";
$wording_lan["discount"] = "Discount";
$wording_lan["totalpv"] = "Total&nbsp;PV";
$wording_lan["report1"] = "Report of an order from Center ";
$wording_lan["report2"] = "Bill ";
$wording_lan["totalmoney"] = "Total&nbsp;Amount";
$wording_lan["wording1"] = "Complete property";
$wording_lan["wording2"] = "Not Complete";
$wording_lan["wording3"] = "ขาดอยู่";
$wording_lan["wording4"] = "คุณสมบัติ";
$wording_lan["wording5"] = "Not maintain balance";
$wording_lan["wording6"] = "Maintain perfect balance";
$wording_lan["wording7"] = "No position";
$wording_lan["wording8"] = "Date code and member information";
$wording_lan["wording9"] = "Start date must be less than or equal End date. Please enter new dates.";
$wording_lan["wording10"] = "Pick dates and Invent Code field in question.";

//Chart
$wording_lan["endleft"] = "End Left";
$wording_lan["endright"] = "End Right";

//Button
$wording_lan["loginbutton"] = "Login";
$wording_lan["submit"] = "Submit";
$wording_lan["search"] = "Search";
$wording_lan["to_text"] = "To";
$wording_lan["printall"] = "Print All";
$wording_lan["print"] = "Print";

//Profile
$wording_lan["topic1"] = "Applicant Information";
$wording_lan["topic2"] = "Business Data";
$wording_lan["ptitle"] = "Title";
$wording_lan["name-surname"] = "Name-Surname";
$wording_lan["nameb"] = "Business Name";
$wording_lan["way"] = "Left/Right";
$wording_lan["password"] = "รหัสผ่าน";
$wording_lan["mcode"] = "Member&nbsp;Code";
$wording_lan["name"] = "Member&nbsp;Name";
$wording_lan["name_e"] = "Name(Eng) ";
$wording_lan["sex"] = "Sex";
$wording_lan["age"] = "Age ";
$wording_lan["occupation"] = "Job ";
$wording_lan["mobile"] = "Mobile ";
$wording_lan["address"] = "Address ";
$wording_lan["district"] = "District";
$wording_lan["province"] = "Province ";
$wording_lan["mar_name"] = "Couple Name ";
$wording_lan["birthday"] = "BirthDay ";
$wording_lan["national"] = "Nationality ";
$wording_lan["status"] = "Status";
$wording_lan["home_t"] = "Telephone  ";
$wording_lan["fax"] = "Fax  ";
$wording_lan["amphur"] = "Amper ";
$wording_lan["zip"] = "PostCode  ";
$wording_lan["mar_age"] = "Sex  ";
$wording_lan["id_tax"] = "passport ";
$wording_lan["id_card"] = "ID card";
$wording_lan["pos_cur"] = " Position ";
$wording_lan["PV"] = "Total&nbsp;PV";
$wording_lan["acc_no"] = "Account ID";
$wording_lan["acc_name"] = "Account&nbsp;Name";
$wording_lan["bankcode"] = "Bank";
$wording_lan["branch"] = "Branch   ";
$wording_lan["sp_name"] = "Sponsor&nbsp;Name";
$wording_lan["sp_code"] = "Sponser&nbsp;Code";
$wording_lan["upa_name"] = "Upline&nbsp;Name";
$wording_lan["upa_code"] = "Upline&nbsp;Code";
$wording_lan["beneficiaries"] = "Beneficiaries";
$wording_lan["relation"] = "Relationship";
$wording_lan["startdate"] = "Register&nbsp;Date";
$wording_lan["sponserd"] = "sponserd";

//Profile
$wording_lan["mcode"] = "Member&nbsp;Code  ";
$wording_lan["name"] = "Member&nbsp;Name";

//Public 
$wording_lan["Title"] = "Welcome !!";
$wording_lan["Footer"] = "Copyright @ 2013 by MLM SYSTEM.";
$wording_lan["UnderConstruction"] = "ขออภัยกับความไม่สะดวก ระบบกำลังประมวลผลอยู่ กรุณากลับเข้ามาใหม่อีกครั้งในอีกครึ่งชั่วโมง ขอบคุณมาก";
$wording_lan["Date"] = "Date";
$wording_lan["PayDate"] = "Pay Date";
$wording_lan["Revenues"] = "Revenue";
$wording_lan["tax"] = "Tax";
$wording_lan["Amount"] = "Net";
$wording_lan["CalDate"] = "Computation Date";
$wording_lan["Recruit"] = "Recruit";
$wording_lan["Binary"] = "Binary";
$wording_lan["OldLeft"] = "Old Left";
$wording_lan["OldRight"] = "Right-old";
$wording_lan["NewLeft"] = "New Left";
$wording_lan["NewRight"] = "New Right";
$wording_lan["TotalLeft"] = "Total left";
$wording_lan["TotalRight"] = "Total right";
$wording_lan["InLeft"] = "เข้าซ้าย";
$wording_lan["InRight"] = "เข้าขวา";
$wording_lan["LessLeft"] = "เหลือซ้าย";
$wording_lan["LessRight"] = "เหลือขวา";
$wording_lan["jub"] = "Match.";
$wording_lan["adjust"] = "adjust";
$wording_lan["Matching"] = "Matching";
$wording_lan["Display"] = "Display";
$wording_lan["Item"] = "Item(s)";
$wording_lan["From"] = "From";
$wording_lan["Each"] = "Each";
$wording_lan["Bonus"] = "Bonus";
$wording_lan["rcode"] = "Code cycle";
$wording_lan["rcode_text"] = "Cycle";
$wording_lan["sdate"] = "วันที่เพิ่มรอบ";
$wording_lan["fdate"] = "Start date";
$wording_lan["tdate"] = "End date";
$wording_lan["promotion"] = "Promotion";
$wording_lan["to"] = " To ";
$wording_lan["TotalEnd"] = "The end of the calculation ";
$wording_lan["AmountEnd"] = "The duration was calculated";
$wording_lan["Second"] = "Seconds.";
$wording_lan["acc_no"] = "Account number";
$wording_lan["acc_name"] = "Account";
$wording_lan["acc_type"] = "Bank";
$wording_lan["commission"] = "Commission";
$wording_lan["old_poscur"] = "Old Position";
$wording_lan["new_poscur"] = "New Position";
$wording_lan["lv"] = "level";
$wording_lan["gen"] = "gen";
$wording_lan["sano"] = "Bill&nbsp;No.";
$wording_lan["uid"] = "Recorder";
$wording_lan["type"] = "Type";
$wording_lan["allpv"] = "PV Cumulative";
$wording_lan["statuspv"] = "PV รักษายอด";
$wording_lan["newstatuspv"] = "PV รักษายอดล่วงหน้า";
$wording_lan["dateposcur"] = "Qualified&nbsp;Date";
$wording_lan["man"] = "Man";
$wording_lan["woman"] = "Woman";
$wording_lan["check"] = "Check";
$wording_lan["insert"] = "Insert";
$wording_lan["cancel"] = "Cancel";
$wording_lan["del"] = "Delete";
$wording_lan["home_t"] = "Home&nbsp;Tel.";
$wording_lan["homg_f"] = "Fax";
$wording_lan["mobile"] = "Mobile(Cell Phone)";
$wording_lan["passport"] = "Passport";
$wording_lan["inv_code"] = "Invent&nbsp;Code";
$wording_lan["inv_name"] = "Invent&nbsp;Name";
$wording_lan["pcode"] = "Product&nbsp;Code";
$wording_lan["pdesc"] = "Product&nbsp;Name";
$wording_lan["price"] = "Price";
$wording_lan["quantity"] = "Quantity";
$wording_lan["code_number"] = "Number of applicants";
$wording_lan["code_number_text"] = "Code";

//login
$wording_lan["Note"] = "Note";
$wording_lan["login_1"] = "Members do not have a password. Please contact head office to ask for your password";
$wording_lan["login_2"] = "Please enter your Member Code and password, then press [Login]";
$wording_lan["login_3"] = "Member Code ";
$wording_lan["login_4"] = "Password ";
$wording_lan["login_5"] = "เข้าระบบ ";
$wording_lan["login_6"] = "Branch ";
$wording_lan["login_7"] = "ได้ login เข้าสู่ระบบเรียบร้อยแล้ว";
$wording_lan["login_8"] = "Change password";

//login invent
$wording_lan["login_9"] = "Please enter your Username and Password, then press [Login]";

//Menu Header
$wording_lan["Header1"] = "Sales";
$wording_lan["Header2"] = "Commission";
$wording_lan["Info1"] = "Calculate commissions to date ";

//sessiontab=1 Sale
$wording_lan["tab1_1"] = "Sales";
$wording_lan["tab1_2"] = "Member";
$wording_lan["tab1_3"] = "Add Member";
$wording_lan["tab1_4"] = "Bill of sales (Purchase order of its members)";
$wording_lan["tab1_5"] = "Sales Bill (Statement)";
$wording_lan["tab1_6"] = "Bill to sell Mobile (Mobile)";
$wording_lan["tab1_7"] = "Bill of order ";
$wording_lan["tab1_8"] = "Bill of order (Purchase order of its member or center)";
$wording_lan["tab1_9"] = "Bill of order from company ";
$wording_lan["tab1_10"] = "Stock";
$wording_lan["tab1_11"] = "Report";
$wording_lan["tab1_12"] = "Summary Ewallet Spending";
$wording_lan["tab1_13"] = "บิลขายให้ Mobile (Mobile)";
$wording_lan["tab1_14"] = "Member List";
$wording_lan["tab1_15"] = "Organization Chart";

//sessiontab=1&sub=2
$wording_lan["sub12_1"] = "Old password ";
$wording_lan["sub12_2"] = "New password ";
$wording_lan["sub12_3"] = "Confirm New password ";
$wording_lan["sub12_4"] = "Old Password is wrong ";
$wording_lan["sub12_5"] = "Try again ";
$wording_lan["sub12_6"] = "To change the password to take effect immediately ";
$wording_lan["sub12_7"] = "Please login ";
$wording_lan["sub12_8"] = "Login. ";
$wording_lan["sub12_9"] = "There was an error in editing the database ";
$wording_lan["sub12_10"] = "Try again ";

//sessiontab=1&sub=2
$wording_lan["tab2_1"] = "Detail reports monthly bonus points (C)";
$wording_lan["tab2_2"] = "Summary income. Monthly commissions (C)";
$wording_lan["tab2_3"] = "Bill Detail ";
$wording_lan["tab2_4"] = "Profile Score ";
$wording_lan["tab2_5"] = "Income commission monthly ";

//sessiontab=3-6
$wording_lan["tab3-6_1"] = "Order";
$wording_lan["tab3-6_2"] = "Add Order  ";

//sessiontab=3&sub=16
$wording_lan["tab3-16_1"] = "Add Order  ";

//sessiontab=3-27
$wording_lan["tab3-27_1"] = "Purchase&nbsp;Date";
$wording_lan["tab3-27_2"] = "Incoming&nbsp;Balance";
$wording_lan["tab3-27_3"] = "Money&nbsp;Received";
$wording_lan["tab3-27_4"] = "Money&nbsp;Paid";
$wording_lan["tab3-27_5"] = "Action";

//sessiontab=4-1
$wording_lan["tab4-1_1"] = "Statement(Company)";
$wording_lan["tab4-1_2"] = "Sale&nbsp;to&nbsp;Mobile";
$wording_lan["tab4-1_3"] = "Statement";
$wording_lan["tab4-1_4"] = "For&nbsp;Qualify";
$wording_lan["tab4-1_5"] = "Maintain&nbsp;Order";
$wording_lan["tab4-1_6"] = "Maintain&nbsp;Order(Immediately)";

//sessiontab=4-2
$wording_lan["tab4-2_1"] = "Bonus(%)";

//sessiontab=4-3
$wording_lan["tax5"] = "Tax(5%)";
$wording_lan["tab4-3_1"] = "Net&nbsp;Income";

//sessiontab=3&tab=667
$wording_lan["tab3_5"] = "Upline";
$wording_lan["tab3_6"] = "Sponsor";


/////////////////////////////////////////////////////////////

// header 
$wording_lan["header_1"] = "สมาชิก";
$wording_lan["header_2"] = "รายงาน";
$wording_lan["header_3"] = "รับของ";
$wording_lan["header_4"] = "Supervisor";
$wording_lan["header_5"] = "แก้ไขรหัสผ่าน";
$wording_lan["header_6"] = "เติมเงิน";

// mem_mainmenu
$wording_lan["mem_mainmenu_1"] = "ทะเบียนสมาชิก Member";
$wording_lan["mem_mainmenu_2"] = "รหัสผู้ใช้";
$wording_lan["mem_mainmenu_3"] = "ชื่อผู้ใช้";
$wording_lan["mem_mainmenu_4"] = "รายชื่อสมาชิกทั้งหมด";
$wording_lan["mem_mainmenu_5"] = "รายชื่อสมาชิกในประเทศ";
$wording_lan["mem_mainmenu_6"] = "รายงานองค์กรไบนารี่";
$wording_lan["mem_mainmenu_7"] = "ข้อมูลสมาชิก";
$wording_lan["mem_mainmenu_8"] = "เพิ่มสมาชิก";
$wording_lan["mem_mainmenu_9"] = "แผนภูมิสายงานสมาชิก";
$wording_lan["mem_mainmenu_10"] = "ผังสายงานยูนิเลเวล";
$wording_lan["mem_mainmenu_11"] = "ข้อมูลสมาชิก ไม่มีอัพไลน์ ";
$wording_lan["mem_mainmenu_12"] = " ข้อมูลสมาชิก  ไม่มีผู้แนะนำ";
$wording_lan["mem_mainmenu_13"] = "แผนภูมิต้นไม้ของสมาชิก";
$wording_lan["mem_mainmenu_14"] = "แผนภูมิต้นไม้ของผู้แนะนำ";
$wording_lan["mem_mainmenu_15"] = "ข้อมูลธนาคารของสมาชิก";
$wording_lan["mem_mainmenu_16"] = "ข้อมูลที่อยู่ของสมาชิก";
$wording_lan["mem_mainmenu_17"] = "ยินดีต้อนรับ";
$wording_lan["mem_mainmenu_18"] = "รายชื่อสมาชิกในประเทศ";
$wording_lan["mem_mainmenu_19"] = "เมนูสมาชิก";
$wording_lan["mem_mainmenu_20"] = "แผนภูมิองค์กรไบนารี่";
$wording_lan["mem_mainmenu_21"] = "ผังสายงานผู้แนะนำ";
$wording_lan["mem_mainmenu_22"] = "รายงานผู้แนะนำ";


 // first page

$wording_lan["first_1"] = "รหัส";
$wording_lan["first_2"] = "ชื่อ";
$wording_lan["first_3"] = "เปลี่ยนรหัสผ่านผู้ใช้งานระบบ";
$wording_lan["first_4"] = "ออกจากระบบ";
$wording_lan["first_5"] = "ชื่อ-นามสกุล";

//sessiontab=1&sub=2
$wording_lan["sub12_1"] = "รหัสผ่านเดิม ";
$wording_lan["sub12_2"] = "รหัสใหม่ ";
$wording_lan["sub12_3"] = "ยืนยันรหัสผ่านใหม่ ";
$wording_lan["sub12_4"] = "รหัสผ่านเดิมไม่ถูกต้อง ";
$wording_lan["sub12_5"] = "ลองใหม่ ";
$wording_lan["sub12_6"] = "การเปลี่ยนรหัสผ่านมีผลใช้งานทันที ";
$wording_lan["sub12_7"] = "กรุณาเข้าสู่ระบบใหม่ ";
$wording_lan["sub12_8"] = "เข้าสู่ระบบ ";
$wording_lan["sub12_9"] = "เกิดข้อผิดพลาดในการแก้ไขฐานข้อมูล ";
$wording_lan["sub12_10"] = "ลองใหม่ ";

// Sub1 member_editadd
$wording_lan["tab1_mem_1"] ="ข้อมูลผู้แนะนำ";
$wording_lan["tab1_mem_2"] ="ข้อมูลอัพไลน์";
$wording_lan["tab1_mem_3"] ="(ปปปป-ดด-วว)";
$wording_lan["tab1_mem_4"] ="รหัสผู้แนะนำ";
$wording_lan["tab1_mem_5"] ="รหัสอัพไลน์";
$wording_lan["tab1_mem_6"] ="ชื่อผู้แนะนำ";
$wording_lan["tab1_mem_7"] ="ชื่ออัพไลน์";
$wording_lan["tab1_mem_8"] ="Location Base";
$wording_lan["tab1_mem_9"] ="ด้าน";
$wording_lan["tab1_mem_10"] ="Member Type";
$wording_lan["tab1_mem_11"] ="ข้อมูลผู้สมัคร";
$wording_lan["tab1_mem_12"] ="ข้อมูลผู้สมัครร่วม";
$wording_lan["tab1_mem_13"] ="คำนำหน้าชื่อ";
$wording_lan["tab1_mem_14"] ="เลือกคำนำหน้า";
$wording_lan["tab1_mem_15"] ="นาย";
$wording_lan["tab1_mem_16"] ="นางสาว";
$wording_lan["tab1_mem_17"] ="นาง";
$wording_lan["tab1_mem_18"] ="บริษัทจำกัด";
$wording_lan["tab1_mem_19"] ="ห้างหุ้นส่วนจำกัด";
$wording_lan["tab1_mem_20"] ="ชื่อ-นามสกุล หรือ ชื่อนิติบุคคล";
$wording_lan["tab1_mem_21"] ="Name & LastName or Company Name";
$wording_lan["tab1_mem_21_s"] ="Name & LastName";
$wording_lan["tab1_mem_22"] ="ชื่อเจ้าของนิติบุคคล";
$wording_lan["tab1_mem_23"] ="เพศ";
$wording_lan["tab1_mem_24"] ="วันที่เกิด";
$wording_lan["tab1_mem_25"] ="สัญชาติ ";
$wording_lan["tab1_mem_26"] ="เลขประจำตัวประชาชน/พาสปอร์ต";
$wording_lan["tab1_mem_27"] ="เลขทะเบียนนิติบุคคล";
$wording_lan["tab1_mem_28"] ="โทรศัพท์บ้าน";
$wording_lan["tab1_mem_29"] ="โทรศัพท์มือถือ";
$wording_lan["tab1_mem_30"] ="โทรสาร";
$wording_lan["tab1_mem_31"] ="อีเมลล์";
$wording_lan["tab1_mem_32"] ="ชาย";
$wording_lan["tab1_mem_33"] ="หญิง";
$wording_lan["tab1_mem_34"] ="อายุต้องไม่ต่ำกว่า 18 ปี";
$wording_lan["tab1_mem_35"] ="ไทย";
$wording_lan["tab1_mem_36"] ="ลาว";
$wording_lan["tab1_mem_37"] ="ที่อยู่ตามทะเบียนบ้าน";
$wording_lan["tab1_mem_38"] ="ที่อยู่สำหรับจัดส่ง / ส่งเอกสาร ที่เดียวกับที่อยู่ทะเบัยนบ้าน";
$wording_lan["tab1_mem_39"] ="เลขที่/ห้อง";
$wording_lan["tab1_mem_40"] ="อาคาร";
$wording_lan["tab1_mem_41"] ="หมู่บ้าน/คอนโด";
$wording_lan["tab1_mem_42"] ="ตรอก/ซอย";
$wording_lan["tab1_mem_43"] ="ถนน";
$wording_lan["tab1_mem_44"] ="Sub-District";
$wording_lan["tab1_mem_45"] ="District";
$wording_lan["tab1_mem_46"] ="Province";
$wording_lan["tab1_mem_47"] ="รหัสไปรษณีย์";
$wording_lan["tab1_mem_48"] ="ข้อมูลการรับผลประโยชน์";
$wording_lan["tab1_mem_49"] ="ผู้รับผลประโยชน์กรมธรรม์ประกันอุบัติเหตุ";
$wording_lan["tab1_mem_50"] ="ธนาคาร";
$wording_lan["tab1_mem_51"] ="สาขา";
$wording_lan["tab1_mem_52"] ="ประเภทบัญชี";
$wording_lan["tab1_mem_53"] ="เลขที่บัญชี";
$wording_lan["tab1_mem_54"] ="ชื่อบัญชี";
$wording_lan["tab1_mem_55"] ="หมายเหตุ";
$wording_lan["tab1_mem_56"] ="ชื่อ-นามสกุล";
$wording_lan["tab1_mem_57"] ="ความสัมพันธ์";
$wording_lan["tab1_mem_58"] ="โทรศัพท์ ";
$wording_lan["tab1_mem_59"] ="หลักฐานครบ";
$wording_lan["tab1_mem_60"] ="ใบสมัคร";
$wording_lan["tab1_mem_61"] =" สำเนาบัตรประชาชนผู้สมัครหลัก";
$wording_lan["tab1_mem_62"] ="สำเนาบัญชีธนาคารผู้สมัครหลัก";
$wording_lan["tab1_mem_63"] ="สำเนาบัตรประชาชนผู้สมัครร่วม ";
$wording_lan["tab1_mem_64"] ="ข้อมูลอื่นๆ";
$wording_lan["tab1_mem_65"] ="รับนิตยสาร";
$wording_lan["tab1_mem_66"] ="จัดส่ง ";
$wording_lan["tab1_mem_67"] ="รับเอง";
$wording_lan["tab1_mem_68"] ="บันทึก";
$wording_lan["tab1_mem_69"] ="ยกเลิก";
$wording_lan["tab1_mem_70"] ="ออมทรัพย์";
$wording_lan["tab1_mem_71"] ="เลือกสาขา";
$wording_lan["tab1_mem_72"] ="ไม่ได้อยู่ในสายงาน";
$wording_lan["tab1_mem_73"] ="รหัสสมาชิก";
$wording_lan["tab1_mem_74"] ="กรุณาเลือกการชำระเงิน";
$wording_lan["tab1_mem_75"] ="กรุณาเลือกวันที่เกิด";
$wording_lan["tab1_mem_76"] ="กรุณาเลือกเดือนที่เกิด";
$wording_lan["tab1_mem_77"] ="กรุณาเลือกปีที่เกิด";
$wording_lan["tab1_mem_78"] ="กรุณาเลือกวันที่เกิดของผู้สมัครร่วม";
$wording_lan["tab1_mem_79"] ="กรุณาเลือกเดือนที่เกิดของผู้สมัครร่วม";
$wording_lan["tab1_mem_80"] ="กรุณาเลือกปีที่เกิดของผู้สมัครร่วม";
$wording_lan["tab1_mem_81"] ="กรอกคำนำหน้า ผู้สมัครร่วม";
$wording_lan["tab1_mem_82"] =",คำนำหน้าชื่อ";
$wording_lan["tab1_mem_83"] =",ชือผู้สมัคร";
$wording_lan["tab1_mem_84"] =",วันเกิด";
$wording_lan["tab1_mem_85"] =",เพศ";
$wording_lan["tab1_mem_86"] =",วันเกิด";
$wording_lan["tab1_mem_87"] =",รหัสผู้แนะนำผิดพลาดกรุณากดค้น";
$wording_lan["tab1_mem_88"] =",ที่อยู่ตามบัตรประชาชน เลขที่ / ห้อง ";
$wording_lan["tab1_mem_89"] =",ที่อยู่ตามบัตรประชาชน จังหวัด ";
$wording_lan["tab1_mem_90"] =",ที่อยู่ตามบัตรประชาชน อำเภอ ";
$wording_lan["tab1_mem_91"] =",ที่อยู่ตามบัตรประชาชน ตำบล ";
$wording_lan["tab1_mem_92"] =",ที่อยู่ตามบัตรประชาชน รหัสไปรษณีย์ ";
$wording_lan["tab1_mem_93"] =",ที่อยู่จัดส่ง เลขที่ / ห้อง ";
$wording_lan["tab1_mem_94"] =",ที่อยู่จัดส่ง จังหวัด ";
$wording_lan["tab1_mem_95"] =",ที่อยู่จัดส่ง อำเภอ ";
$wording_lan["tab1_mem_96"] =",ที่อยู่จัดส่ง ตำบล ";
$wording_lan["tab1_mem_97"] =",ที่อยู่จัดส่ง รหัสไปรษณีย์ ";
$wording_lan["tab1_mem_98"] =",คำนำหน้าชื่อ ผู้รับกรมธรรม์";
$wording_lan["tab1_mem_99"] =",ความสัมพันธ์ ผู้รับกรมธรรม์";
$wording_lan["tab1_mem_100"] =",โทรศัพท์ ผู้รับกรมธรรม์";
$wording_lan["tab1_mem_101"] =",เลขที่บัตรประชาชน ผู้รับกรมธรรม์";
$wording_lan["tab1_mem_102"] ="รูปแบบ Email ไม่ถูกต้อง";
$wording_lan["tab1_mem_103"] =",วันที่สมัคร";
$wording_lan["tab1_mem_104"] =",มือถือ";
$wording_lan["tab1_mem_105"] =",มือถือของผู้สมัครร่วม";
$wording_lan["tab1_mem_106"] =",เลขบัตรประชาชน ";
$wording_lan["tab1_mem_107"] ="เลขบัตรประชาชนไม่ถูกต้่อง";
$wording_lan["tab1_mem_108"] ="เลขบัตรประชาชนของผู้สมัครร่วมไม่ถูกต้อง";
$wording_lan["tab1_mem_109"] =",เลขบัตรประชาชนของผู้สมัครร่วม";
$wording_lan["tab1_mem_111"] =",เลขบัตรประชาชน/พาสปอร์ต ";
$wording_lan["tab1_mem_112"] =",เลขบัตรประชาชนคู่สมรส ";
$wording_lan["tab1_mem_113"] =",รหัสผู้แนะนำ";
$wording_lan["tab1_mem_114"] ="กรุณาเลือกซ้ายขวา";
$wording_lan["tab1_mem_115"] =",เลขที่บัญชี";
$wording_lan["tab1_mem_116"] ="ไปหน้าสมาชิก";
$wording_lan["tab1_mem_117"] ="ไม่พบข้อมูล";
$wording_lan["tab1_mem_118"] =",กรอกเพศ ผู้สมัครร่วม";
$wording_lan["tab1_mem_119"] =",กรอกเลขบัตรประชาชน ผู้สมัครร่วม";
$wording_lan["tab1_mem_120"] ="ข้อมูลธุรกิจ";
$wording_lan["tab1_mem_121"] ="ตรวจ";
$wording_lan["tab1_mem_122"] ="เลือก";
$wording_lan["tab1_mem_123"] ="ลบ";
$wording_lan["tab1_mem_124"] ="วันที่สมัคร";
$wording_lan["tab1_mem_125"] ="ซ้าย";
$wording_lan["tab1_mem_126"] ="ขวา";
$wording_lan["tab1_mem_127"] ="บุคคลธรรมดา";
$wording_lan["tab1_mem_128"] ="นิติบุคคล";
$wording_lan["tab1_mem_129"] ="วัน";
$wording_lan["tab1_mem_130"] ="เดือน";
$wording_lan["tab1_mem_131"] ="ปี(พ.ศ)";
$wording_lan["tab1_mem_132"] ="ที่อยู่สำหรับจัดส่ง / ส่งเอกสาร";
$wording_lan["tab1_mem_133"] ="ที่เดียวกับที่อยู่ตามบัตรประชาชน";
$wording_lan["tab1_mem_134"] ="หลักฐาน";
$wording_lan["tab1_mem_135"] ="ชำระโดย";
$wording_lan["tab1_mem_136"] ="เงินสด ";
$wording_lan["tab1_mem_137"] ="บัตรเครดิต";
$wording_lan["tab1_mem_138"] ="เงินโอน ";
$wording_lan["tab1_mem_139"] ="หมายเหตุ ";
$wording_lan["tab1_mem_140"] ="ตรวจสอบ";
$wording_lan["tab1_mem_141"] ="คลิกตรวจสอบเพื่อทำการตรวจสอบข้อมูล ";

// Sub1 member_editadd ---end

// sub 3 ดูข้อมูลสมาชิก
$wording_lan["tab2_sale_1"]= "บิลขายทั้งหมด";
$wording_lan["tab2_sale_2"]= "สาขา";
$wording_lan["tab2_sale_3"]= "บิลแจงยอด";
$wording_lan["tab2_sale_4"]= "บิล Autoship";
$wording_lan["tab1_50"]= "บิลส่ง Stockist";
$wording_lan["tab2_sale_51"]= "บิลส่ง Stockist ทั้งหมด";
$wording_lan["tab2_sale_52"]= "บิลส่ง Stockist ของสาขา";
$wording_lan["tab2_sale_6"]= "บิลรับของ";
$wording_lan["tab2_sale_7"]= "เติมเงิน Ewallet";
$wording_lan["tab2_sale_8"]= "บิลเติมเงินทั้งหมด";
$wording_lan["tab2_sale_9"]= "บิลเติมเงินสาขา";
$wording_lan["tab2_sale_10"]= "รายงาน";
$wording_lan["tab2_sale_11"]= "ยอดสินค้าที่ถูกขาย";
$wording_lan["tab2_sale_12"]= "ใบสรุป รายการขายสินค้าระหว่างวันที่";
$wording_lan["tab2_sale_13"]= "ใบสรุป สรุปรายการรับเงิน";
$wording_lan["tab2_sale_14"]= "ข้อมูลสินค้า";
$wording_lan["tab2_sale_15"]= "เพิ่มสินค้า";
$wording_lan["tab2_sale_16"]= "ยืนยันเอกสาร";
$wording_lan["tab2_sale_17"]= "ข้อมูลสินค้านำเข้า";
$wording_lan["tab2_sale_18"]= "ส่งสินค้าระหว่างสาขา";
$wording_lan["tab2_sale_19"]= "เพิ่มการส่งสินค้าระหว่างสาขา";
$wording_lan["tab2_sale_20"]= "บิลแจงยอด";
$wording_lan["tab2_sale_21"]= "รายงานยอดสินค้าที่ถูกขาย";
$wording_lan["tab2_sale_22"]= "ใบสรุป รายการขายสินค้าระหว่างวันที่";
$wording_lan["tab2_sale_23"]= "แจงยอด";
$wording_lan["tab2_sale_24"]= "สมัครสมาชิก";
$wording_lan["tab2_sale_25"]= "ใบสรุป รายการรับเงิน";
$wording_lan["tab2_sale_26"]= "บิลแจงยอด";
$wording_lan["tab2_sale_27"]= "ใบสรุป รายการรับเงิน Ewallet ระหว่างวันที่";
$wording_lan["tab2_sale_28"]= "ใบสรุป รายการรับเงิน Ewallet ระหว่างวันที่";
$wording_lan["tab2_sale_29"]= " บิลส่งของ Stockist";
$wording_lan["tab2_sale_30"]= "เพิ่มบิลส่งของ Stockist";
$wording_lan["tab2_sale_31"] = "สาขา";
$wording_lan["tab2_sale_32"] = "เพิ่มสมาชิก";
$wording_lan["tab2_sale_33"] = "บิลรับของ";
$wording_lan["tab2_sale_34"] = "รายการสั่งซื้อ Autoship";
$wording_lan["tab2_sale_35"] = "บิลเติมเงินทั้งหมด";
$wording_lan["tab2_sale_36"] = "เติมเงิน";
$wording_lan["tab2_sale_37"] = "บิลขายทั้งหมด";
$wording_lan["tab2_sale_38"] = "บิลเติมเงินสาขา";
$wording_lan["tab2_sale_39"] = "รายงาน";
$wording_lan["tab2_sale_40"] = "บันทึกรายการค่าใช่จ่ายศูนย์";
$wording_lan["tab2_sale_41"] = "เพิ่มรายการค่าใช้จ่ายศูนย์";

////// Report
$wording_lan["Report_1"] = "รหัสสมาชิก";
$wording_lan["Report_2"] = "ชื่อ";
$wording_lan["Report_3"] = "รหัสประชาชน";
$wording_lan["Report_4"] = "วันที่สมัคร";
$wording_lan["Report_5"] = "วันหมดอายุ";
$wording_lan["Report_6"] = "ตำแหน่ง";
$wording_lan["Report_7"] = "เข็ม";
$wording_lan["Report_8"] = "รหัสผู้แนะนำ";
$wording_lan["Report_9"] = "เอกสาร";
$wording_lan["Report_10"] = "Suspend";
$wording_lan["Report_11"] = "Terminate";
$wording_lan["Report_12"] = "Autoship";
$wording_lan["Report_13"] = "LB";
$wording_lan["Report_14"] = "รหัสอัพไลน์";
$wording_lan["Report_15"] = "ดู";
$wording_lan["Report_16"] = "Voucher";
$wording_lan["Report_17"] = "Ewallet";
$wording_lan["Report_19"] = "เข็ม";
$wording_lan["Report_20"] = "เกียรติยศ";
$wording_lan["Report_21"] = "ด้าน";


//Billall
$wording_lan["Bill_print"] ="พิมพ์";
$wording_lan["Bill_view"] ="ดู";
$wording_lan["Bill_cancle"] ="ยกเลิก";
$wording_lan["Bill_1"] ="วันที่ซื้อ";
$wording_lan["Bill_2"] ="เลขบิล";
$wording_lan["Bill_3"] ="รหัสผู้ซื้อ";
$wording_lan["Bill_4"] ="ชื่อผู้ซื้อ";
$wording_lan["Bill_5"] ="ชนิด";
$wording_lan["Bill_6"] ="PV";
$wording_lan["Bill_7"] ="จำนวนเงิน";
$wording_lan["Bill_8"] ="ผู้คีย์";
$wording_lan["Bill_9"] ="จัดส่ง";
$wording_lan["Bill_10"] ="วันจัดส่ง ";
$wording_lan["Bill_11"] ="วันรับของ";
$wording_lan["Bill_12"] ="อ้างอิง";
$wording_lan["Bill_13"] ="ซื้อสาขา";
$wording_lan["Bill_14"] ="รับของสาขา";
$wording_lan["Bill_15"] ="user<br>จัดส่ง";
$wording_lan["Bill_16"] ="user<br>รับของ";
$wording_lan["Bill_17"] ="ช่องทาง";
$wording_lan["Bill_18"] ="จำนวนรวม PV";
$wording_lan["Bill_19"] ="จำนวนเงินรวม";
$wording_lan["Bill_20"] ="พนักงาน";
$wording_lan["Bill_21"] ="ต้องการยกเลิกบิลนี้";
$wording_lan["Bill_22"] ="ต้องการเปลี่ยนแปลงการรับของ";
$wording_lan["Bill_23"] ="ต้องการเปลี่ยนแปลงจัดส่ง";
$wording_lan["Bill_24"] ="สาขา";

// header bill  
$wording_lan["Billjang_1"] ="เลขบิล";
$wording_lan["Billjang_2"] ="รหัสผู้ซื้อ";
$wording_lan["Billjang_3"] ="ชื่อผู้ซื้อ";
$wording_lan["Billjang_4"] ="วันที่ซื้อ";
$wording_lan["Billjang_41"] ="วันที่แจง";
$wording_lan["Billjang_5"] ="จำนวนรวมPV";
$wording_lan["Billjang_6"] ="จำนวนเงินรวม";
$wording_lan["Billjang_7"] ="เลขที่บิลHold";
$wording_lan["Billjang_8"] ="รหัสผู้ซื้อHold";
$wording_lan["Billjang_9"] ="ชื่อผู้ซื้อHold";
$wording_lan["Billjang_10"] ="ผู้บันทึก";
$wording_lan["Billjang_11"] ="เงินสด";
$wording_lan["Billjang_12"] ="เงินโอน";
$wording_lan["Billjang_13"] ="บัตรเครดิต";
$wording_lan["Billjang_14"] ="พนักงาน";
$wording_lan["Billjang_15"] ="สาขา";
$wording_lan["Billjang_16"] ="ช่องทาง";
$wording_lan["Billjang_17"] ="สาขาหรือพนักงาน";
$wording_lan["Billjang_loding"] ="โหลด";
$wording_lan["Billjang_cre"] ="สร้าง";
$wording_lan["Billjang_20"] ="";
$wording_lan["Billjang_21"] ="";
$wording_lan["Billjang_22"] ="";
$wording_lan["Billjang_23"] ="";
$wording_lan["Billjang_24"] ="";
$wording_lan["Billjang_25"] ="";
$wording_lan["Billjang_26"] ="";
$wording_lan["Billjang_27"] ="";
$wording_lan["Billjang_28"] ="";
$wording_lan["Billjang_29"] ="";
$wording_lan["Billjang_30"] ="";

// ewallet
$wording_lan["ewallet_1"] ="ไม่ได้อยู่ในสายงาน";
$wording_lan["ewallet_2"] ="รหัสสมาชิก";
$wording_lan["ewallet_3"] ="ยอดเงิน";
$wording_lan["ewallet_4"] =" บาท กรุณาเลือกวิธีชำระเงินให้ครบตามจำนวน";
$wording_lan["ewallet_5"] ="วันที่";
$wording_lan["ewallet_6"] ="รหัสสาขา";
$wording_lan["ewallet_7"] ="คลิกตรวจสอบเพื่อทำการตรวจสอบข้อมูล";
$wording_lan["ewallet_8"] ="ลำดับ";
$wording_lan["ewallet_9"] ="รหัส";
$wording_lan["ewallet_10"] ="รายละเอียด";
$wording_lan["ewallet_11"] ="ราคา";
$wording_lan["ewallet_12"] ="PV";
$wording_lan["ewallet_13"] ="BV";
$wording_lan["ewallet_14"] ="FV";
$wording_lan["ewallet_15"] ="จำนวน";
$wording_lan["ewallet_16"] ="รวมราคา";
$wording_lan["ewallet_17"] ="รวมPV";
$wording_lan["ewallet_18"] ="รวมBV";
$wording_lan["ewallet_19"] ="รวมFV";
$wording_lan["ewallet_20"] = "เลือกข้อมูลสอนค้าจากตารางขวามือ แล้วแก้ไขจำนวนตามต้องการ";
$wording_lan["ewallet_21"] = "ไปหน้าสมาชิก";
$wording_lan["ewallet_22"] = "ไม่พบข้อมูล";
$wording_lan["ewallet_23"] = "วันที่";
$wording_lan["ewallet_24"] = "เติมเงิน";
$wording_lan["ewallet_25"] = "เงินสด";
$wording_lan["ewallet_26"] = "รายละเอียด";
$wording_lan["ewallet_27"] = "เงินโอน";
$wording_lan["ewallet_28"] = "บัตรเครดิตใบที่ 1";
$wording_lan["ewallet_29"] = "บัตรเครดิตใบที่ 2";
$wording_lan["ewallet_30"] = "บัตรเครดิตใบที่ 3";
$wording_lan["ewallet_31"] = "หมายเหตุ";
$wording_lan["ewallet_32"] = "รวม";



//รับของ case 3

$wording_lan["send_1"] = "รับของ";
$wording_lan["send_2"] = "บิลจัดส่ง";
$wording_lan["send_3"] = "บิลจัดส่งชุดสมัคร";
$wording_lan["send_33"] = "บิลจัดส่งรอยืนยันรับชุดสมัคร";
$wording_lan["send_44"] = "บิลจัดส่งรอยืนยันรับสินค้า";
$wording_lan["send_4"] = "บิลจัดส่งสินค้า";
$wording_lan["send_5"] = "รับของที่สาขา";
$wording_lan["send_6"] = "บิลรับชุดสมัครที่สาขา (รอรับของ)";
$wording_lan["send_7"] = "บิลรับของที่สาขา (รอรับของ)";
$wording_lan["send_61"] = "บิลรับชุดสมัครที่สาขา";
$wording_lan["send_71"] = "บิลรับของที่สาขา";
$wording_lan["send_8"] = "บิลขายรับสาขา";
$wording_lan["send_9"] = "รายการใบเบิกสินค้าจากคลังสำนักงานใหญ่";
$wording_lan["send_10"] = "เพิ่มใบเบิกสินค้าจากคลังสำนักงานใหญ่";
$wording_lan["send_11"] = "ที่อยู่จัดส่ง";
$wording_lan["send_12"] = "มือถือ";
$wording_lan["send_13"] = "ส่งของ";


//supervisor

$wording_lan["supervisor_1"] = "Confirm เงินโอน";
$wording_lan["supervisor_2"] = "รายงานการสมัครออนไลน์";
$wording_lan["supervisor_3"] = "รายงานที่ซื้อสินค้าผ่านทางหน้าเว็บ";
$wording_lan["supervisor_4"] = "รายงานการเติมเงิน Ewallet ผ่านทางหน้าเว็บ";
$wording_lan["supervisor_5"] = "ข้อมูลรอบการคำนวณรอบการจ่าย";
$wording_lan["supervisor_6"] = "รายงานสรุปรอบการจ่าย";
$wording_lan["supervisor_7"] = "รายงานสรุปรอบการไม่จ่าย";
$wording_lan["supervisor_8"] = "รายงานสรุป Pack File";
$wording_lan["supervisor_9"] = "รายงานรวมการจ่าย คอมมิชชั่น (Local Currency)";
$wording_lan["supervisor_10"] = "Commission";
$wording_lan["supervisor_11"] = "รหัสสมาชิก";
$wording_lan["supervisor_12"] = "ชื่อ";
$wording_lan["supervisor_13"] = "รหัสประชาชน";
$wording_lan["supervisor_14"] = "วันที่สมัคร";
$wording_lan["supervisor_15"] = "รหัสผู้แนะนำ";
$wording_lan["supervisor_16"] = "โอนแล้ว";
$wording_lan["supervisor_17"] = "บัตรเครดิต";
$wording_lan["supervisor_18"] = "บิลอ้างอิง";
$wording_lan["supervisor_19"]  = "เลขใบสั่งซื้อ";
$wording_lan["supervisor_20"]  = "รหัสสมาชิก";
$wording_lan["supervisor_21"]  = "ชื่อ";
$wording_lan["supervisor_22"]  = "เบอร์โทร";
$wording_lan["supervisor_23"]  = "เป็นเงิน";
$wording_lan["supervisor_24"]  = "โอนแล้ว";
$wording_lan["supervisor_25"]  = "บัตรเครดิต";
$wording_lan["supervisor_26"]  = "รูปแบบ";
$wording_lan["supervisor_27"]  = "บิลอ้างอิง";
$wording_lan["supervisor_28"]  = "รหัสรอบ";
$wording_lan["supervisor_29"]  = "วันที่เพิ่มรอบ";
$wording_lan["supervisor_30"]  = "วันที่คำนวนเริ่มต้น";
$wording_lan["supervisor_31"]  = "วันที่คำนวณสิ้นสุด";
$wording_lan["supervisor_32"]  = "เริ่มรักษายอด";
$wording_lan["supervisor_33"]  = "สิ้นสุดรักษายอด";
$wording_lan["supervisor_34"]  = "คำนวณแล้ว";
$wording_lan["supervisor_35"]  = "เวลาที่กดคำนวน";
$wording_lan["supervisor_36"]  = "Clear ยอด";
$wording_lan["supervisor_37"]  = "กรุณากรอกรูปแบบรอบให้ถูกต้อง";
$wording_lan["supervisor_38"]  = "รอบเริ่มต้น ต้องน้อยกว่าหรือเท่ากับ รอบสิ้นสุด กรุณาใส่รอบการคำนวณใหม่";
$wording_lan["supervisor_39"]  = " ถึง";
$wording_lan["supervisor_40"]  = "รอบ";
$wording_lan["supervisor_41"]  = "รหัส";
$wording_lan["supervisor_42"]  = "ชื่อ";
$wording_lan["supervisor_43"]  = "ยอดยกมา";
$wording_lan["supervisor_44"]  = "ยอดเดือนนี้";
$wording_lan["supervisor_45"]  = "ยอดรวมจ่าย";
$wording_lan["supervisor_46"]  = "กรอกรอบ และรหัสสมาชิกที่ต้องการดูรายงาน";
$wording_lan["supervisor_47"]  = "รอบ";
$wording_lan["supervisor_48"]  = "( กรอกข้อมูลเป็น 1-9 )";
$wording_lan["supervisor_49"]  = "รหัสสมาชิก";
$wording_lan["supervisor_50"]  = "ดูรายงาน";
$wording_lan["supervisor_51"]  = "ยอดยกไป";
$wording_lan["supervisor_52"]  = "คลิกดูรายละเอียดรอบ";
$wording_lan["supervisor_53"]  = "บันทึกรายการค่าใช่จ่ายศูนย์";
$wording_lan["supervisor_54"]  = "";
$wording_lan["supervisor_55"]  = "";
$wording_lan["supervisor_56"]  = "";



//sessiontab=2
$wording_lan["tab2_5"] = "ดู PV ย้อนหลัง";
$wording_lan["tab2_back"] = " ย้อนหลัง";
$wording_lan["tab2_1_search"] = "ค้นหา";
$wording_lan["tab2_1_nomember"] = "ไม่มีสมาชิก";
// memchart_f3c  & f3c1
$wording_lan["tab2_1_1"] = "ไม่สามารถดูข้อมูลได้เพราะไม่พบชื่อสมาชิก" ;
$wording_lan["tab2_1_2"] = "กลับไปยังแผนภูมิสายงานสมาชิก";
$wording_lan["tab2_1_3"] = "ไม่สามารถดูข้อมูลในระดับสูงกว่าได้";
$wording_lan["tab2_1_4"] = "ไม่สามารถดูข้อมูลต่างสายงานได้";
$wording_lan["tab2_1_month"]= "เดือน";
$wording_lan["tab2_1_member"]= "สมาชิก";
// Profile block left
$wording_lan["tab2_1_5"] = "รหัสสมาชิก";
$wording_lan["tab2_1_6"] = "วันที่สมัคร ";
$wording_lan["tab2_1_7"] = "วันหมดอายุ";
$wording_lan["tab2_1_8"] = "ระดับการสมัคร";
$wording_lan["tab2_1_9"] = "ตำแหน่งสูงสุด";
$wording_lan["tab2_1_10"] = "ระดับรับ Matching ล่าสุด";
$wording_lan["tab2_1_11"] = "ตำแหน่ง Star";
$wording_lan["tab2_1_12"] = "ผู้แนะนำ";
$wording_lan["tab2_1_13"] = "ใบสมัครสมาชิก";
$wording_lan["tab2_1_14"] = "สำเนาบัตรประชาชนผู้สมัครหลัก";
$wording_lan["tab2_1_15"] = "สำเนาบัญชีธนาคารผู้สมัครหลัก";
$wording_lan["tab2_1_16"] = "สำเนาบัตรประชาชนผู้สมัครร่วม";
// PV block Right
$wording_lan["tab2_1_17"] = "PV ส่วนตัวเดือนนี้";
$wording_lan["tab2_1_18"] = "PV ส่วนตัวสะสม 60 วันแรก";
$wording_lan["tab2_1_19"] = "PV ซ้าย (ยกมา)";
$wording_lan["tab2_1_20"] = "PV ซ้าย (เดือนนี้)";
$wording_lan["tab2_1_21"] = "PV ซ้าย (รวม)";
$wording_lan["tab2_1_212"] = "PV ซ้าย (สะสม)";
$wording_lan["tab2_1_213"] = "PV ขวา (สะสม)";
$wording_lan["tab2_1_22"] = "PV ขวา (ยกมา)";
$wording_lan["tab2_1_23"] = "PV ขวา (เดือนนี้)";
$wording_lan["tab2_1_24"] = "PV ขวา (รวม)";
$wording_lan["tab2_1_25"] = "Hold PV ซ้าย (HOLD)";
$wording_lan["tab2_1_26"] = "Hold PV ขวา (HOLD)";
$wording_lan["tab2_1_27"] = "Cycle เดือนนี้";
$wording_lan["tab2_1_28"] = "Star ติดตัวสรุปยอดทุกวันที่ 1";
$wording_lan["tab2_1_29"] = "Star Sup";
$wording_lan["tab2_1_30"] = "Star Ex";
$wording_lan["tab2_1_31"] = "PV ส่วนตัว";
$wording_lan["tab2_1_complete"] = "ครบถ้วน";
$wording_lan["tab2_1_incomplete"] = "ไม่ครบ" ;
$wording_lan["tab2_1_nonposition"] = "ไม่มีตำแหน่ง";
  //ChartGEN-----
$wording_lan["tab2_chartgen_1"] = "ครบคุณสมบัติ เหลือ" ;
$wording_lan["tab2_chartgen_2"] = "ไม่ครบ(ขาดอยู่" ;
$wording_lan["tab2_chartgen_3"] = "PV ส่วนตัวเดือนนี้" ;
$wording_lan["tab2_chartgen_4"] = "ซ้ายเก่า" ;
$wording_lan["tab2_chartgen_5"] = "ขวาเก่า" ;
$wording_lan["tab2_chartgen_6"] = "ซ้ายใหม่" ;
$wording_lan["tab2_chartgen_7"] = "ขวาใหม่" ;
$wording_lan["tab2_chartgen_8"] = "ซ้ายรวม" ;
$wording_lan["tab2_chartgen_9"] = "ขวารวม" ;
$wording_lan["tab2_chartgen_10"] = "คลิกเพื่อเพิ่มข้อมูลสมาชิก" ;
$wording_lan["tab2_chartgen_11"] = "ยังไม่รักษายอด" ;
$wording_lan["tab2_chartgen_12"] = "รักษายอดสมบูรณ์" ;
$wording_lan["tab2_chartgen_top"] = "บน";
$wording_lan["tab2_chartgen_rimright"] = "ขวา" ;
$wording_lan["tab2_chartgen_rimleft"] = "ซ้าย";
$wording_lan["tab2_chartgen_left"] = "ซ้าย" ;
$wording_lan["tab2_chartgen_rihght"] = "ขวา" ;
  //ChartGEN----- end

/////////////////////////////////////////////////////
$wording_lan["tab2_report_01"] = "รายงาน";
$wording_lan["tab2_report_02"] = "รายงานรายการขายและสมัครสมาชิก";
$wording_lan["tab2_report_03"] = "รายงานรายการเติมเงิน Ewallet";
$wording_lan["tab2_report_04"] = "สรุปยอดรายการขายและเติมเงิน Ewallet, Eautoship";
$wording_lan["tab2_report_06"] = "รายงานการรับชำระเงินประจำวัน แยกตามเคาน์เตอร์และประเภทการชำระ(ขาย)";
$wording_lan["tab2_report_07"] = "รายงานการรับชำระเงินประจำวัน แยกตามเคาน์เตอร์และประเภทการชำระ(เติมเงิน)";

$wording_lan["tab2_report_05"] = "ใบสรุป รายการสั่งซื้อสินค้าระหว่างวันที่";

$wording_lan["tab2_report_1"] = "วันที่";
$wording_lan["tab2_report_2"] = "ถึง";
$wording_lan["tab2_report_3"] = "ซื้อแบบ";
$wording_lan["tab2_report_4"] = "ทั้งหมด";
$wording_lan["tab2_report_5"] = "ซื้อแบบปกติ";
$wording_lan["tab2_report_6"] = "ซื้อแบบ Hold";
$wording_lan["tab2_report_7"] = "การจัดส่ง";
$wording_lan["tab2_report_8"] = "จัดส่ง";
$wording_lan["tab2_report_9"] = "รับเอง";
$wording_lan["tab2_report_10"] = "PV รวม ";
$wording_lan["tab2_report_11"] = "ประเภท ";
$wording_lan["tab2_report_12"] = "สมัคร";
$wording_lan["tab2_report_13"] = "ต่ออายุ" ;
$wording_lan["tab2_report_14"] = "ซื้อของ" ;
$wording_lan["tab2_report_15"] = "จำนวนเงินรวม" ;
$wording_lan["tab2_report_16"] = "ผู้บันทึก" ;
$wording_lan["tab2_report_17"] = "ช่องทาง" ;
$wording_lan["tab2_report_18"] = "HQ" ;
$wording_lan["tab2_report_19"] = "ATO" ;
$wording_lan["tab2_report_20"] = "Branch" ;
$wording_lan["tab2_report_21"] = "ONLINE" ;
$wording_lan["tab2_report_22"] = "เลขบิล";
$wording_lan["tab2_report_23"] = "เลขบิลแจง" ;
$wording_lan["tab2_report_24"] = "สาขา" ;
$wording_lan["tab2_report_25"] = "วันที่" ;
$wording_lan["tab2_report_26"] = "รหัสผู้ซื้อ" ;
$wording_lan["tab2_report_27"] = "รหัสผู้สปอนเซอร์" ;
$wording_lan["tab2_report_28"] = "ผู้บันทึก" ;

$wording_lan["tab2_report_29"] = "ลำดับ";
$wording_lan["tab2_report_30"] = "เลขบิล";
$wording_lan["tab2_report_31"] = "รหัสผู้ซื้อ";
$wording_lan["tab2_report_32"] = "ชื่อผู้ซื้อ";
$wording_lan["tab2_report_33"] = "ซื้อแบบ";
$wording_lan["tab2_report_34"] = "วันที่ซื้อ";
$wording_lan["tab2_report_35"] = "จำนวนรวมPV";
$wording_lan["tab2_report_36"] = "จำนวนเงินรวม";
$wording_lan["tab2_report_37"] = "เงินสด";
$wording_lan["tab2_report_38"] = "เครดิต";
$wording_lan["tab2_report_39"] = "เงินโอน";
$wording_lan["tab2_report_40"] = "คูปอง";
$wording_lan["tab2_report_41"] = "ผู้บันทึก";
$wording_lan["tab2_report_42"] = "สาขา";
$wording_lan["tab2_report_43"] = "ช่องทาง";
$wording_lan["tab2_report_44"] = "จัดส่ง";
$wording_lan["tab2_report_45"] = "ประเภท";

$wording_lan["tab2_report_46"] = "รายงานรายการเติมเงิน Ewallet";
$wording_lan["tab2_report_47"] = "สรุปยอดรายการขายและเติมเงิน Ewallet";

$wording_lan["tab3_3_1"] = "จากวันที่";
$wording_lan["tab3_3_2"] = "ถึงวันที่";
$wording_lan["tab3_3_3"] = "จำนวนบิล";
$wording_lan["tab3_3_4"] = "จำนวนเงินรวม";
$wording_lan["tab3_3_5"] = "เงินสด";
$wording_lan["tab3_3_6"] = "เครดิต";
$wording_lan["tab3_3_7"] = "Ewallet";
$wording_lan["tab3_3_8"] = "เงินโอน";
$wording_lan["tab3_3_9"] = "ส่วนลด";
$wording_lan["tab3_3_10"] = "User";
$wording_lan["tab3_3_11"] = "สาขา";
$wording_lan["tab3_3_12"] = "ช่องทาง";
$wording_lan["tab3_3_13"] = "ไปยังหน้า";
$wording_lan["tab3_3_14"] = "Enter เพื่อไปยังหน้าที่ต้องการ";


$wording_lan["tab2_billedit"]["1"] = "สั่งซื้อสินค้าออนไลน์ ";
$wording_lan["tab2_billedit"]["1_1"] = "รูปแบบการซื้อ";
$wording_lan["tab2_billedit"]["1_2"] = "รหัสสมาชิก";
$wording_lan["tab2_billedit"]["1_3"] = "วันที่";
$wording_lan["tab2_billedit"]["1_4"] = "จัดส่ง";
$wording_lan["tab2_billedit"]["1_5"] = "ไม่จัดส่ง";
$wording_lan["tab2_billedit"]["1_6"] = "รับที่สาขา";
$wording_lan["tab2_billedit"]["1_7"] = "เลือกวิธีการชำระเงิน";
$wording_lan["tab2_billedit"]["1_8"] = "เลือกรูปแบบการซื้อ";
$wording_lan["tab2_billedit"]["1_9"] = "ซื้อแบบปกติ";
$wording_lan["tab2_billedit"]["1_10"] = "ซื้อแบบ Hold";
$wording_lan["tab2_billedit"]["1_11"] = "Ewallet";
$wording_lan["tab2_billedit"]["1_12"] = "Voucher+Ewallet";
$wording_lan["tab2_billedit"]["1_13"] = "บัตรเครดิต";
$wording_lan["tab2_billedit"]["1_14"] = "โอนเงิน";
$wording_lan["tab2_billedit"]["1_15"] = "กรอกข้อมูลที่อยู่สำหรับจัดส่งใหม่ หรือ";
$wording_lan["tab2_billedit"]["1_16"] = "ส่งสินค้าตามที่อยู่ที่ได้แจ้งไว้กับบริษัทฯ";
$wording_lan["tab2_billedit"]["1_17"] = "ชื่อผู้รับ";
$wording_lan["tab2_billedit"]["1_18"] = "เบอร์ติดต่อ";
$wording_lan["tab2_billedit"]["1_19"] = "ที่อยู่";
$wording_lan["tab2_billedit"]["1_20"] = "จังหวัด";
$wording_lan["tab2_billedit"]["1_21"] = "อำเภอ";
$wording_lan["tab2_billedit"]["1_22"] = "ตำบล";
$wording_lan["tab2_billedit"]["1_23"] = "รหัสไปรษณีย์";
$wording_lan["tab2_billedit"]["1_24"] = "ค้นหา";
$wording_lan["tab2_billedit"]["1_25"] = "หมายเหตุ ";
$wording_lan["tab2_billedit"]["1_26"] = "ตกลง ";
$wording_lan["tab2_billedit"]["1_27"] = "ไม่ได้อยู่ในสายงาน หรือ <br>ไม่สามารถสั่งซื้อข้ามประเทศ";

$wording_lan["tab2_billedit"]["1_28"] = "ลำดับ";
$wording_lan["tab2_billedit"]["1_29"] = "รหัส";
$wording_lan["tab2_billedit"]["1_30"] = "รายละเอียด";
$wording_lan["tab2_billedit"]["1_31"] = "ราคา";
$wording_lan["tab2_billedit"]["1_32"] = "PV";
$wording_lan["tab2_billedit"]["1_33"] = "จำนวน";
$wording_lan["tab2_billedit"]["1_34"] = "รวมราคา";
$wording_lan["tab2_billedit"]["1_35"] = "รวมPV";
$wording_lan["tab2_billedit"]["1_36"] = "ลบ";
$wording_lan["tab2_billedit"]["1_37"] = "ตรวจสอบ";
$wording_lan["tab2_billedit"]["1_38"] = "บันทึก";
$wording_lan["tab2_billedit"]["1_39"] = "ยกเลิก";
$wording_lan["tab2_billedit"]["1_40"] = "ไม่สามารถใส่ค่า 0 หรือ ช่องว่างได้";
$wording_lan["tab2_billedit"]["1_41"] = "คลิกตรวจสอบเพื่อทำการตรวจสอบข้อมูล";
$wording_lan["tab2_billedit"]["1_42"] = "คุณต้องรักษายอดทันที่เป็นจำนวน";
$wording_lan['tab2_billedit']['1_43'] = "และ รักษายอดทันทีได้ไม่เกิน";
$wording_lan['tab2_billedit']['1_44'] = "คุณได้รักษายอดครบคุณสมบัติล่วงหน้าไปแล้ว";
$wording_lan['tab2_billedit']['1_45'] = "รักษายอดได้ไม่เกิน";
$wording_lan['tab2_billedit']['1_46'] = "ไม่ได้อยู่ในระบบ";
$wording_lan['tab2_billedit']['1_47'] = "คุณได้รักษายอดครบคุณสมบัติไปแล้ว";
$wording_lan['tab2_billedit']['1_48'] = "Ewallet ของท่านไม่เพียงพอ";
$wording_lan['tab2_billedit']['1_49'] = "Voucher ใช้ซื้อสินค้าให้กับ รหัสสมาชิก";
$wording_lan['tab2_billedit']['1_50'] = "ได้เท่านั้น";
$wording_lan['tab2_billedit']['1_51'] = "Voucher+Ewallet ของท่านไม่เพียงพอ";
$wording_lan['tab2_billedit']['1_52'] = "กรุณาเลือกรูปแบบการจัดส่ง";
$wording_lan['tab2_billedit']['1_53'] = "กรุณาใส่ชื่อ คนรับของด้วย";
$wording_lan['tab2_billedit']['1_54'] = "กรุณาใส่เบอร์โทรคนรับของด้วย";
$wording_lan['tab2_billedit']['1_55'] = "กรุณาใส่ที่อยู่";
$wording_lan['tab2_billedit']['1_56'] = "กรุณาเลือกจังหวัด";
$wording_lan['tab2_billedit']['1_57'] = "กรุณาเลือกอำเภอ";
$wording_lan['tab2_billedit']['1_58'] = "กรุณาเลือกตำบล";
$wording_lan['tab2_billedit']['1_59'] = "กรุณารหัสไปรษณีย์";
$wording_lan['tab2_billedit']['1_60'] = "รับที่สาขา";
$wording_lan['tab2_billedit']['1_61'] = "กรุณากดค้นสาขา";
$wording_lan['tab2_billedit']['1_62'] = "เลือกข้อมูลสอนค้าจากตารางขวามือ แล้วแก้ไขจำนวนตามต้องการ";
$wording_lan['tab2_billedit']['1_63'] = "ไปหน้าสมาชิก";
$wording_lan['tab2_billedit']['1_64'] = "ไม่สามารถแก้ไขบิลนี้ได้";
$wording_lan['tab2_billedit']['1_65'] = "เลือก";
$wording_lan['tab2_billedit']['1_66'] = "น้ำหนักรวม";
$wording_lan['tab2_billedit']['1_67'] = "กิโลกรัม";
$wording_lan['tab2_billedit']['1_68'] = " ค่าจัดส่ง";
$wording_lan['tab2_billedit']['1_69'] = " ยอดรวมใหม่";
$wording_lan['tab2_billedit']['1_70'] = "ข้อมูลในช่อง";
$wording_lan['tab2_billedit']['1_71'] = " มีอยู่ในระบบแล้ว";
$wording_lan['tab2_billedit']['1_72'] = "เป็นรหัสที่อยู่ในชั้นล่างกว่า";
$wording_lan['tab2_billedit']['1_73'] = "เป็นรหัสตัวเองไม่ได้";
$wording_lan['tab2_billedit']['1_74'] = "ไม่ได้กรอก";
$wording_lan['tab2_billedit']['1_75'] = "ต้องมีความยาว";
$wording_lan['tab2_billedit']['1_76'] = "เท่านั้น";
$wording_lan['tab2_billedit']['1_78'] = "กรณีจ่ายด้วย Discount ระบบจะไม่คิด PV ให้";
$wording_lan['tab2_billedit']['1_79'] = "สินค้า";
$wording_lan['tab2_billedit']['1_80'] = "แพคเก็จ";
$wording_lan['tab2_billedit']['1_81'] = "ยอดเงิน";
$wording_lan['tab2_billedit']['1_82'] = "กรุณาเลือกวิธีชำระเงินให้ครบตามจำนวน";
$wording_lan['tab2_billedit']['1_83'] = "บาท";
$wording_lan['tab2_billedit']['1_84'] = "รวม";
$wording_lan['tab2_billedit']['1_85'] = "ไม่พบข้อมูล";
$wording_lan['tab2_billedit']['1_86'] = "เลือกข้อมูลจากรายการสินค้า และแก้ไขจำนวนตามต้องการ";
$wording_lan['tab2_billedit']['1_87'] = "ไม่พบรายการสินค้าของบิลเลขที่";

// Productshow 
$wording_lan["productshow"]["1"] = "รหัส";
$wording_lan["productshow"]["2"] = "รายละเอียด";
$wording_lan["productshow"]["3"] = "ราคา";
$wording_lan["productshow"]["4"] = "คะแนน";
$wording_lan["productshow"]["5"] = "ค้นหา";
$wording_lan["productshow"]["6"] = "ประเภทผลิตภัณฑ์";

$wording_lan["operate"]["1"] = "เพิ่มธนาคาร";
$wording_lan["operate"]["2"] = "แก้ไขข้อมูลธนาคาร";
$wording_lan["operate"]["3"] = "ไม่สามารถเปิดบิล ข้ามประเทศได้";
$wording_lan["operate"]["4"] = "Voucher+Ewallet ไม่เพียงพอ มีค่าการจัดส่งเพิ่ม";
$wording_lan["operate"]["5"] = "เพิ่มบิล";
$wording_lan["operate"]["6"] = "พบข้อผิดพลาดในการบันทึกกรุณาลองใหม่อีกครั้ง";
$wording_lan["operate"]["7"] = "ewallet ไม่เพียงพอ มีค่าการจัดส่งเพิ่ม ";
$wording_lan["operate"]["8"] = "ไม่สามารถเปิดบิลแจงซ้ำได้";
$wording_lan["operate"]["9"] = "ไม่สามารถแจงยอดข้ามประเทศได้";
$wording_lan["operate"]["10"] = "ไม่สามารถสมัคร ข้ามประเทศได้";
$wording_lan["operate"]["11"] = "Ewallet ไม่เพียงพอ";
$wording_lan["operate"]["12"] = "รหัสบัตรประชาขนนี้ได้ทำการสมัครไปเรียบร้อยแล้ว";
$wording_lan["operate"]["13"] = " บาท";
$wording_lan["operate"]["14"] = "ไม่สามารถใช้ Ewallet ข้ามประเทศได้";
$wording_lan["operate"]["15"] = "Ewallet ไม่เพียงพอในการคีย์บิล";
$wording_lan["operate"]["16"] = "Voucher ไม่เพียงพอในการคีย์บิล";
$wording_lan["operate"]["17"] = "Autoship ไม่เพียงพอในการคีย์บิล";


$wording_lan["supervisor_61"] = "รอบที่";
$wording_lan["supervisor_62"] = "ตั้งแต่วันที่";
$wording_lan["supervisor_63"] = "ถึงวันที่";
$wording_lan["supervisor_64"] = "รหัส";
$wording_lan["supervisor_65"] = "ชื่อ-นามสกุล";
$wording_lan["supervisor_66"] = "ยอดยกมา";
$wording_lan["supervisor_67"] = "FOB";
$wording_lan["supervisor_68"] = "Cycle";
$wording_lan["supervisor_69"] = "SMB";
$wording_lan["supervisor_70"] = "Matching";
$wording_lan["supervisor_71"] = "One Time";
$wording_lan["supervisor_72"] = "Bonusรวม";
$wording_lan["supervisor_73"] = "Bonusรวม<br>+ยอดยกมา";
$wording_lan["supervisor_74"] = "Bonus ยกไป<br>(ไม่โอนรอบนี้)";
$wording_lan["supervisor_75"] = "Bonus สะสมทั้งปี";
$wording_lan["supervisor_76"] = "vat";
$wording_lan["supervisor_77"] = "หักภาษี";
$wording_lan["supervisor_78"] = "หักค่าโอน";
$wording_lan["supervisor_79"] = "voucher";
$wording_lan["supervisor_80"] = "สรุปยอดโอน";
$wording_lan["supervisor_81"] = "PV";
$wording_lan["supervisor_82"] = "LB";

$wording_lan["supervisor_83"] = "แผน";
$wording_lan["supervisor_84"] = "ส่งศูนย์";
$wording_lan["Change to BMC"] = "Change to Hold";
$wording_lan["pin"] = "PIN";



$wording_lan["tab4"]["5"] = "ประวัติการเติม Ewallet ";
$wording_lan["tab4"]["5_1"] = "รหัสสมาชิก";
$wording_lan["tab4"]["5_2"] = "วันที่";
$wording_lan["tab4"]["5_3"] = "Ewallet คงเหลือ";
$wording_lan["tab4"]["5_4"] = "เติมเงิน";
$wording_lan["tab4"]["5_5"] = "เลือกวิธีการชำระเงิน";
$wording_lan["tab4"]["5_6"] = "ข้อตกลงและเงื่อนไขการให้บริการ กรณีชำระผ่านบัตรเครดิต";
$wording_lan["tab4"]["5_7"] = "ระบบจะเติม Ewallet ให้ทันที เมื่อรายการได้รับการอนุมัติ กรณีรายการอนุมัติแล้วแต่ยังไม่ได้รับการเติม Ewallet เพื่อความสะดวกและรวดเร็ว กรุณาติดต่อ แผนกดูแลลูกค้า ( Customer Support ) บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ,โทรศัพท์ 02-5415655 ,Email : support@successmore.com";
$wording_lan["tab4"]["5_8"] = "การจัดจำหน่ายสินค้า/บริการ เป็นความรับผิดชอบของ บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด แต่เพียงผู้เดียว เคทีซี ( ผู้ให้บริการชำระผ่านบัตรเครดิต ) ไม่ใช่ผู้จัดจำหน่ายสินค้า/บริการและไม่มีส่วนรับผิดชอบใด ๆ เกี่ยวกับสินค้า/บริการ กรณีสมาชิกมีข้อสงสัยหรือร้องเรียนเกี่ยวกับสินค้า/บริการที่ได้รับ หรือหากต้องการใบเสร็จและใบกำกับภาษี กรุณาติดต่อโดยตรงกับ แผนกดูแลลูกค้า บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด";
$wording_lan["tab4"]["5_9"] = "บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ขอสงวนสิทธิ์ในการยกเลิกหรือเปลี่ยนแปลงใบสั่งซื้อสินค้า/บริการ และถือเป็นการตกลงยืนยันการสั่งซื้อของสมาชิก";
$wording_lan["tab4"]["5_10"] = "บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ขอสงวนสิทธิ์ในการเปลี่ยนแปลงรายการสินค้า ข้อตกลง และเงื่อนไข โดยไม่ต้องแจ้งให้ทราบล่วงหน้าและกรณีมีข้อพิพาท คำตัดสินของบริษัทฯ ถือเป็นที่สิ้นสุด";
$wording_lan["tab4"]["5_11"] = "ข้อตกลงและเงื่อนไขการให้บริการ กรณีชำระผ่านเงินโอนหรือ Bill Payment";
$wording_lan["tab4"]["5_12"] = "เจ้าหน้าที่จะทำการเติม Ewallet ให้ภายใน 1 วัน สำหรับรายการที่บริษัทฯ ได้รับการชำระเงินเรียบร้อยแล้วเท่านั้น กรณีชำระเงินและแจ้งบริษัทฯแล้วแต่ยังไม่ได้รับการเติม Ewallet ภายในระยะเวลาที่กำหนด เพื่อความสะดวกและรวดเร็ว กรุณาติดต่อ แผนกดูแลลูกค้า ( Customer Support ) บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ,โทรศัพท์ 02-5415655 ,Email : support@successmore.com";
$wording_lan["tab4"]["5_13"] = "การจัดจำหน่ายสินค้า/บริการ เป็นความรับผิดชอบของ บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด แต่เพียงผู้เดียว ธนาคารผู้รับชำระ ไม่ใช่ผู้จัดจำหน่ายสินค้า/บริการและไม่มีส่วนรับผิดชอบใด ๆ เกี่ยวกับสินค้า/บริการ กรณีสมาชิกมีข้อสงสัยหรือร้องเรียนเกี่ยวกับสินค้า/บริการที่ได้รับ หรือหากต้องการใบเสร็จและใบกำกับภาษี กรุณาติดต่อโดยตรงกับ แผนกดูแลลูกค้า บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด";
$wording_lan["tab4"]["5_14"] = "ข้าพเจ้าเข้าใจข้อกำหนดและเงื่อนไขต่าง ๆ ตามข้างต้น และตกลงยอมรับผูกพันตามข้อกำหนดและเงื่อนไขดังกล่าวทุกประการ";
$wording_lan["tab4"]["5_15"] = "โอนเงิน";
$wording_lan["tab4"]["5_16"] = "บัตรเครดิต";
$wording_lan["tab4"]["5_17"] = "ตรวจสอบ";
$wording_lan["tab4"]["5_18"] = "บันทึก";
$wording_lan["tab4"]["5_19"] = "ยกเลิก";

///////////////// Email //////////////////
$wording_lan["email"]["welcome"]="Welcome to Proud Network Co.,Ltd";
$wording_lan["email"]["from"] =" Proud Network Information<info@http:// ProudNetwork.net/>";
$wording_lan["email"]["text"]="ยินดีต้อนรับสู่ Proud Network";
$wording_lan["email"]["company"]="Proud Network Co.,Ltd";

$wording_lan["tab2_chartgen_past"] = "เก่า" ;
$wording_lan["tab2_chartgen_present"] = "ใหม่" ;
$wording_lan["tab4"]["8_6"] = "PV รวม";


$wording_lan["tab4"]["25_7"] = "ระบบจะต่ออายุ ให้ทันที เมื่อรายการได้รับการอนุมัติ กรณีรายการอนุมัติแล้วแต่ยังไม่ได้รับการต่ออายุ เพื่อความสะดวกและรวดเร็ว กรุณาติดต่อ แผนกดูแลลูกค้า ( Customer Support ) บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ,โทรศัพท์ 02-5415655 ,Email : support@successmore.com";
$wording_lan["tab4"]["25_8"] = "การจัดจำหน่ายสินค้า/บริการ เป็นความรับผิดชอบของ บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด แต่เพียงผู้เดียว เคทีซี ( ผู้ให้บริการชำระผ่านบัตรเครดิต ) ไม่ใช่ผู้จัดจำหน่ายสินค้า/บริการและไม่มีส่วนรับผิดชอบใด ๆ เกี่ยวกับสินค้า/บริการ กรณีสมาชิกมีข้อสงสัยหรือร้องเรียนเกี่ยวกับสินค้า/บริการที่ได้รับ หรือหากต้องการใบเสร็จและใบกำกับภาษี กรุณาติดต่อโดยตรงกับ แผนกดูแลลูกค้า บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด";
$wording_lan["tab4"]["25_9"] = "บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ขอสงวนสิทธิ์ในการยกเลิกหรือเปลี่ยนแปลงใบสั่งซื้อสินค้า/บริการ และถือเป็นการตกลงยืนยันการสั่งซื้อของสมาชิก";
$wording_lan["tab4"]["25_10"] = "บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ขอสงวนสิทธิ์ในการเปลี่ยนแปลงรายการสินค้า ข้อตกลง และเงื่อนไข โดยไม่ต้องแจ้งให้ทราบล่วงหน้าและกรณีมีข้อพิพาท คำตัดสินของบริษัทฯ ถือเป็นที่สิ้นสุด";
$wording_lan["tab4"]["25_11"] = "ข้อตกลงและเงื่อนไขการให้บริการ กรณีชำระผ่านเงินโอนหรือ Bill Payment";
$wording_lan["tab4"]["25_12"] = "เจ้าหน้าที่จะทำการต่ออายุ ให้ภายใน 1 วัน สำหรับรายการที่บริษัทฯ ได้รับการชำระเงินเรียบร้อยแล้วเท่านั้น กรณีชำระเงินและแจ้งบริษัทฯแล้วแต่ยังไม่ได้รับการต่ออายุ ภายในระยะเวลาที่กำหนด เพื่อความสะดวกและรวดเร็ว กรุณาติดต่อ แผนกดูแลลูกค้า ( Customer Support ) บริษัท ซัคเซสมอร์ บีอิ้งค์ จำกัด ,โทรศัพท์ 02-5415655 ,Email : support@successmore.com";



///////// Global wording //////////////////////

$wording_lan["satype"]["A"] = 'ปกติ';
$wording_lan["satype"]["B"] = 'รักษายอดทันที';
$wording_lan["satype"]["C"] = 'รักษายอดทันที';
$wording_lan["satype"]["Q"] = 'รักษายอดล้วงหน้า';
$wording_lan["satype"]["H"] = 'HOLD';
$wording_lan["logistic"]["1"] = 'จัดส่ง' ;
$wording_lan["logistic"]["2"] =  'รับเอง' ;
$wording_lan["sregister"]["register"]= 'สมัคร';
$wording_lan["sregister"]["extend"]='ต่ออายุ';
$wording_lan["sregister"]["3"]='ซื้อของ' ;
$wording_lan["sspv"]["1"]='HQ' ;
$wording_lan["sspv"]["2"]='ATO' ;
$wording_lan["sspv"]["3"]='Branch' ;
$wording_lan["sspv"]["4"]='Online' ;
$wording_lan["sspv"]["5"]='Stockist' ;
$wording_lan["sspv"]["6"]='ทั้งหมด ไม่รวม Stockist' ;

$wording_lan["tab4"]["1_28"] = "ลำดับ	";
$wording_lan["tab4"]["1_29"] = "รหัส";
$wording_lan["tab4"]["1_30"] = "รายละเอียด";
$wording_lan["tab4"]["1_31"] = "ราคา";
$wording_lan["tab4"]["1_32"] = "PV";
$wording_lan["tab4"]["1_33"] = "จำนวน";
$wording_lan["tab4"]["1_34"] = "รวมราคา";
$wording_lan["tab4"]["1_35"] = "รวมPV";
$wording_lan["tab4"]["1_36"] = "ลบ";
$wording_lan["tab4"]["1_37"] = "ตรวจสอบ";
$wording_lan["tab4"]["1_38"] = "บันทึก";
$wording_lan["tab4"]["1_39"] = "ยกเลิก";

?> 